var sites_data = [
    "https://www.worldsdumbestgame.com",
    "https://supermariobros.io",
    "https://jellymar.io",
    "https://www.tyroneunblockedgames.com",
    "https://www.retrogames.cc",
    "https://www.y8.com/games",
    "https://flappybird.io",
    "http://www.slither.io",
    "https://play2048.co",
    "https://www.y8.com/games/slope",
    "https://en.akinator.com",
    "https://dotsandboxes.org",
    "https://www.autodraw.com",
    "https://quickdraw.withgoogle.com",
    "https://radiooooo.com",
    "https://lines.chromeexperiments.com",
    "https://www.yuichiroharai.com/experiments/fluid",
    "https://stars.chromeexperiments.com",
    "https://you.regettingold.com",
    "https://neal.fun",
    "https://drawastickman.com",
    "https://strobe.cool",
    "https://www.mapcrunch.com",
    "https://www.google.com/sky",
    "https://www.geoguessr.com/game/XgqMpcUBeDEzYrrH",
    "http://www.tinydifferences.com",
    "http://www.webriddles.com",
    "http://www.webriddles.com/allriddles.php",
    "https://www.sotruefacts.com",
    "http://www.thefacesoffacebook.com",
    "http://www.talkobamato.me",
    "https://www.numbeo.com/cost-of-living",
    "https://howsecureismypassword.net",
    "http://www.trypap.com",
    "https://giphy.com",
    "https://willrobotstakemyjob.com",
    "http://www.savethesounds.info",
    "http://www.radio.garden/visit/seattle-wa/PPM2Rql0",
    "https://kickassapp.com",
    "https://futuretimeline.net",
    "http://www.notpron.org/notpron",
    "https://wakeup.isadoradigitalagency.com",
    "https://www.how-old.net",
    "https://asoftmurmur.com",
    "https://findtheinvisiblecow.com",
    "https://www.rankfight.com",
    "https://vole.wtf/perfect-circle",
    "https://neal.fun/life-checklist",
    "https://www.deathtimer.com",
    "https://projects.playables.net/ooo",
    "https://projects.playables.net/keys",
    "https://projects.playables.net/coin",
    "https://projects.playables.net/pointer",
    "https://projects.playables.net/text",
    "https://projects.playables.net/draw",
    "https://projects.playables.net/tree",
    "http://www.astroalpaca.com",
    "http://www.higherlowergame.com",
    "http://dinahmoelabs.com/plink",
    "https://www.agegeek.com",
    "https://unpigeon.me",
    "https://www.yourmetricbirthday.com",
    "https://www.rock-paper-scissors-game.com",
    "https://weboas.is",
    "https://www.eyes-only.net",
    "https://pointerpointer.com",
    "https://zoomquilt.org",
    "http://www.weavesilk.com",
    "https://rave.dj",
    "http://www.essaytyper.com",
    "https://outrider.org/nuclear-weapons/interactive/bomb-blast",
    "http://www.hackertyper.com",
    "https://geekprank.com",
    "https://geekprank.com/hacker",
    "https://geekprank.com/jurassic-park",
    "http://www.geektyper.com",
    "https://animagraffs.com",
    "https://www.szynalski.com/tone-generator",
    "https://lab.nationalmedals.org/gravity",
    "https://www.lookingatsomething.com",
    "http://sampulator.com",
    "https://patatap.com",
    "https://typatone.com",
    "http://lawriecape.co.uk/wiblr",
    "https://avseoul.net/particleEqualizer",
    "https://www.concerthotels.com/got-rhythm",
    "https://paveldogreat.github.io/WebGL-Fluid-Simulation",
    "http://www.staggeringbeauty.com",
    "https://koalastothemax.com",
    "https://chrismckenzie.com",
    "https://rrrgggbbb.com",
    "https://just-shower-thoughts.com",
    "https://bongo.cat",
    "http://www.yesnoif.com",
    "http://www.blankwindows.com",
    "http://heeeeeeeey.com",
    "https://demo.marpi.pl/eyes",
    "https://morsecode.world/international/translator.html",
    "https://alwaysjudgeabookbyitscover.com",
    "http://thatsthefinger.com",
    "https://smashthewalls.com",
    "http://endless.horse",
    "http://lacquerlacquer.com",
    "http://www.crossdivisions.com",
    "http://dogs.are.the.most.moe",
    "http://www.trashloop.com",
    "http://spaceis.cool",
    "https://greatbignothing.com",
    "https://find-a-movie.com",
    "https://whatmovieshouldiwatchtonight.com",
    "https://agoodmovietowatch.com",
    "https://www.justwatch.com",
    "https://gethuman.com",
    "https://10minutemail.com",
    "https://www.fakenamegenerator.com",
    "https://www.flightradar24.com/51.5,-0.12/8",
    "https://www.tunefind.com",
    "https://textsmili.es",
    "http://dongerlist.com"
]

// var sites_data = {
//     games_sites: [
//         "https://www.worldsdumbestgame.com",
//         "https://supermariobros.io",
//         "https://jellymar.io",
//         "https://www.tyroneunblockedgames.com",
//         "https://www.retrogames.cc",
//         "https://www.y8.com/games",
//         "https://flappybird.io",
//         "http://www.slither.io",
//         "https://play2048.co",
//         "https://www.y8.com/games/slope",
//         "https://en.akinator.com",
//         "https://dotsandboxes.org"
//     ],
//     fun_sites: [
//         "https://www.autodraw.com",
//         "https://quickdraw.withgoogle.com",
//         "https://radiooooo.com",
//         "https://lines.chromeexperiments.com",
//         "https://www.yuichiroharai.com/experiments/fluid",
//         "https://stars.chromeexperiments.com",
//         "https://you.regettingold.com",
//         "https://neal.fun",
//         "https://drawastickman.com",
//         "https://strobe.cool",
//         "https://www.mapcrunch.com",
//         "https://www.google.com/sky",
//         "https://www.geoguessr.com/game/XgqMpcUBeDEzYrrH",
//         "http://www.tinydifferences.com",
//         "http://www.webriddles.com",
//         "http://www.webriddles.com/allriddles.php",
//         "https://www.sotruefacts.com",
//         "http://www.thefacesoffacebook.com",
//         "http://www.talkobamato.me",
//         "https://www.numbeo.com/cost-of-living",
//         "https://howsecureismypassword.net",
//         "http://www.trypap.com",
//         "https://giphy.com",
//         "https://willrobotstakemyjob.com",
//         "http://www.savethesounds.info",
//         "http://www.radio.garden/visit/seattle-wa/PPM2Rql0",
//         "https://kickassapp.com",
//         "https://futuretimeline.net",
//         "http://www.notpron.org/notpron",
//         "https://wakeup.isadoradigitalagency.com",
//         "https://www.how-old.net",
//         "https://asoftmurmur.com",
//         "https://findtheinvisiblecow.com",
//         "https://www.rankfight.com",
//         "https://vole.wtf/perfect-circle",
//         "https://neal.fun/life-checklist",
//         "https://www.deathtimer.com",
//         "https://projects.playables.net/ooo",
//         "https://projects.playables.net/keys",
//         "https://projects.playables.net/coin",
//         "https://projects.playables.net/pointer",
//         "https://projects.playables.net/text",
//         "https://projects.playables.net/draw",
//         "https://projects.playables.net/tree",
//         "http://www.astroalpaca.com",
//         "http://www.higherlowergame.com",
//         "http://dinahmoelabs.com/plink",
//         "https://www.agegeek.com",
//         "https://unpigeon.me",
//         "https://www.yourmetricbirthday.com",
//         "https://www.rock-paper-scissors-game.com",
//         "https://theuselessweb.site/hereistoday",
//         "https://theuselessweb.site/ffffidget"
//         "https://theuselessweb.site/niceonedad",
//     ],
//     cool_sites: [
//         "https://weboas.is",
//         "https://www.eyes-only.net",
//         "https://pointerpointer.com",
//         "https://zoomquilt.org",
//         "http://www.weavesilk.com",
//         "https://rave.dj",
//         "http://www.essaytyper.com",
//         "https://outrider.org/nuclear-weapons/interactive/bomb-blast",
//         "http://www.hackertyper.com",
//         "https://geekprank.com",
//         "https://geekprank.com/hacker",
//         "https://geekprank.com/jurassic-park",
//         "http://www.geektyper.com",
//         "https://animagraffs.com",
//         "https://www.szynalski.com/tone-generator",
//         "https://lab.nationalmedals.org/gravity",
//         "https://www.lookingatsomething.com",
//         "http://sampulator.com",
//         "https://patatap.com",
//         "https://typatone.com",
//         "http://lawriecape.co.uk/wiblr",
//         "https://avseoul.net/particleEqualizer",
//         "https://www.concerthotels.com/got-rhythm",
//         "https://paveldogreat.github.io/WebGL-Fluid-Simulation",
//         "https://theuselessweb.site/blueballmachine"
//     ],
//     useless_sites: [
//         "http://www.staggeringbeauty.com",
//         "https://koalastothemax.com",
//         "https://chrismckenzie.com",
//         "https://rrrgggbbb.com",
//         "https://just-shower-thoughts.com",
//         "https://bongo.cat",
//         "http://www.yesnoif.com",
//         "http://www.blankwindows.com",
//         "http://heeeeeeeey.com",
//         "https://demo.marpi.pl/eyes",
//         "https://morsecode.world/international/translator.html",
//         "https://alwaysjudgeabookbyitscover.com",
//         "http://thatsthefinger.com",
//         "https://smashthewalls.com",
//         "http://endless.horse",
//         "http://lacquerlacquer.com",
//         "http://www.crossdivisions.com",
//         "http://dogs.are.the.most.moe",
//         "http://www.trashloop.com",
//         "http://spaceis.cool",
//         "https://theuselessweb.site/coloursquares",
//         "https://theuselessweb.site/fallingguy",
//         "https://theuselessweb.site/fallingfalling",
//         "https://theuselessweb.site/tiling",
//         "https://theuselessweb.site/wewillattack",
//         "https://theuselessweb.site/pleasetouchme",
//         "https://theuselessweb.site/beefchickenpork",
//         "https://theuselessweb.site/hotdoom",
//         "https://theuselessweb.site/feedderpy",
//         "https://greatbignothing.com"
//     ],
//     useful_sites: [
//         "https://find-a-movie.com",
//         "https://whatmovieshouldiwatchtonight.com",
//         "https://agoodmovietowatch.com",
//         "https://www.justwatch.com",
//         "https://gethuman.com",
//         "https://10minutemail.com",
//         "https://www.fakenamegenerator.com",
//         "https://www.flightradar24.com/51.5,-0.12/8",
//         "https://www.tunefind.com",
//         "https://textsmili.es",
//         "http://dongerlist.com",
//         "https://theuselessweb.site/uppertolowercase"
//     ]
// }